### PR TITLE
Add ability to disable icon rotation and complete animation

### PR DESCRIPTION
**Pull request by sgcodigo**
- rotate_icon to enable or disable icon rotation while sliding
- animate_complete to enable or disable animation when slide is complete

## Status
**READY**

## Description
Add the ability to disable icon rotation, and the ability to disable the animation that occurs when slide is completed.

## Related PRs/Issues
N.A

## Todos
- [ ] Tests
- [✓] Documentation
- [ ] Screenshots

## Feedback Reviews

@cortinico

### CODE REVIEW

**Comment by cortinico** [comment]
Hey,

Thanks for the PR,
I'll have a look soon-ish.

The build failed because of a Maven timeout.
Restarted here: https://travis-ci.org/cortinico/slidetoact/builds/416701149

**Comment by cortinico** [comment]
Hey @sgcodico

Thanks again for the contrib.
Can I ask you to have two separate PRs? One for the `rotate_icon` and another for the `animate_complete`.

For the `rotate_icon` I'm ok with that and we should be able to merge it.
For the `animate_complete` I'd love to clean it up a bit to avoid some code duplication.

**Comment by cortinico** [comment]
@sgcodigo Need some support for the other PR?

**Comment by sgcodigo** [comment]
Apologies, been busy with work. Will update it this coming weekend. :)

**Comment by cortinico** [comment]
Great looking forward :)

**Comment by sgcodigo** [comment]
Closing this PR due to #22 and #38

**Pull request closed without merging**
