### PR TITLE
Upgrade targetSdkVersion to 29

### PR DESCRIPTION
**Pull request by abhijeet-nkt**
Upgraded the targetSdkVersion to 29

Appearantly, the library doesn't violates any API change. The warning on line 284 of the ```SlideToActView``` class turned into an error which was fixed by a simple null check.

### CODE REVIEW

**Comment by cortinico** [comment]
You need to update those as well in order to make Travis green:
https://github.com/cortinico/slidetoact/blob/8dad98676a26cf3d249929e8db9cc2b951e2812b/.travis.yml#L9-L11

**Comment by abhijeet-nkt** [comment]
Done

**Comment by abhijeet-nkt** [comment]
Woops 😬

**Comment by abhijeet-nkt** [comment]
The error asks to accept the license agreement, I wonder how'd that be done on a CI ? 🤷🏻‍♂️

**Comment by cortinico** [comment]
> The error asks to accept the license agreement, I wonder how'd that be done on a CI ? 🤷🏻‍♂️

You can use this as inspiration:
https://github.com/mvmike/min-cal-widget/blob/master/.travis.yml

**Comment by abhijeet-nkt** [comment]
Pass!

**Pull request merged**
