### PR TITLE
Make class open for inherit

### PR DESCRIPTION
**Pull request by CharifMakaoui**
just a test i don't know any thing on kotlin
https://stackoverflow.com/questions/45648361/can-not-inherit-from-final-class

## Status
**READY/IN DEVELOPMENT/HOLD**

## Description
A few sentences describing the overall goals of the pull request's commits.

## Related PRs/Issues
List related PRs and Issues for this Pull Request.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Screenshots

## Feedback Reviews

@cortinico

### CODE REVIEW

**Comment by cortinico** [comment]
Hey @CharifMakaoui 

Thanks for the Pull Request :D 

So the class was intentionally designed for not being extended.
You're not supposed to subclass a `SlideToActView` as it already offers a lot of methods for customisation.

I'm closing this for now.
Can you please explain why you wanted this to be merged and/or specify your use case?

**Comment by CharifMakaoui** [comment]
screenshot_385
I want to get this result

**Comment by cortinico** [comment]
Hey @CharifMakaoui 
So the feature you request is already on master. Will be available in the upcoming version `0.5.0`

**Comment by cortinico** [comment]
So it's available on `0.5.0`, just released!

**Pull request closed without merging**
