### PR TITLE
Add text rotation

### PR DESCRIPTION
**Pull request by adrienrx**
## Description
Add the ability to rotate the inner text.
## Related PRs/Issues
#3 Slide from right to left 
## Comments
I've added a use case in the text/style example app.

### CODE REVIEW

**Comment by adrienrx** [comment]
## Description
Add the ability to rotate the inner text.
## Related PRs/Issues
#3 Slide from right to left 
##Comments
I've added a use case in the text/style example app.

**Comment by sebasira** [comment]
Will it be merged? I'm lookig forward to use this feature

**Comment by cortinico** [comment]
Hey @sebasira,
I'm currently a bit busy organizing an Android Conference: https://devfest.gdgpisa.it

I'll do the review just after (like next week).
Ideally yes, this is probably going to be merge :) We probably need some minor tweaks.

**Comment by adrienrx** [comment]
@cortinico, this GDG event looks wicked! Such a shame flights are so expensive from London. I would had definitely joined hehe! 

Let me know when you get some time, I'll update the PR according your comments ;)

🚀

**Comment by cortinico** [comment]
Sure thanks for your patience @adrienrx :)

**Comment by cortinico** [comment]
Hey @adrienrx @sebasira Can I ask you to take a look at #67 ?
I ended up implementing it without the `rotate=180` that should be definitely more maintainable on the long run. Looking forward your feedback :)

**Comment by cortinico** [comment]
PS: Thanks for the patience :)

**Comment by adrienrx** [comment]
waiting

**Pull request closed without merging**
